=== vojtechnerad/mobile-catalog/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://example.com/nerv01/mobilni-katalog"
    xmlns="http://example.com/nerv01/mobilni-katalog"
    xmlns:mk="http://example.com/nerv01/mobilni-katalog" elementFormDefault="qualified">

    <xs:element name="devices" type="devicesType">
        <xs:key name="deviceIdKey">
            <xs:selector xpath="mk:device"/>
            <xs:field xpath="@id"/>
        </xs:key>

        <xs:keyref refer="manufacturersKey" name="brandConfirmation">
            <xs:selector xpath="mk:device"/>
            <xs:field xpath="mk:brand"/>
        </xs:keyref>
    </xs:element>

    <xs:complexType name="devicesType">
        <xs:sequence>
            <xs:element name="manufacturers" type="manufacturersType">
                <xs:key name="manufacturersKey">
                    <xs:selector xpath="mk:manufacturer"/>
                    <xs:field xpath="."/>
                </xs:key>
            </xs:element>

            <xs:element name="device" type="deviceType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="manufacturersType">
        <xs:sequence>
            <xs:element name="manufacturer" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="deviceType">
        <xs:sequence>
            <xs:element name="brand" type="xs:string"/>
            <xs:element name="model" type="modelType"/>
            <xs:element name="releasedate" type="xs:date"/>
            <xs:element name="color" type="xs:string"/>
            <xs:element name="price" type="priceType"/>
            <xs:element name="image" type="imageType"/>
            <xs:element name="display" type="displayType"/>
            <xs:element name="chipset" type="chipsetType"/>
            <xs:element name="cameras" type="camerasType"/>
            <xs:element name="memory" type="memoryType"/>
            <xs:element name="system" type="systemType"/>
            <xs:element name="battery" type="batteryType"/>
            <xs:element name="connectors" type="connectorsType"/>
            <xs:element name="comms" type="commsType"/>
            <xs:element name="features" type="featuresType"/>
            <xs:element name="body" type="bodyType"/>
            <xs:element name="categories" type="categoriesType"/>
        </xs:sequence>
        <xs:attribute type="xs:integer" name="id" use="required"/>
    </xs:complexType>

    <xs:complexType name="modelType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="code" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="priceType">
        <xs:simpleContent>
            <xs:extension base="xs:decimal">
                <xs:attribute name="currency" type="currencyType" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="currencyType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="CZK"/>
            <xs:enumeration value="EUR"/>
            <xs:enumeration value="USD"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="imageType">
        <xs:attribute name="src" type="srcType" use="required"/>
    </xs:complexType>
    
    <xs:simpleType name="srcType">
        <xs:restriction base="xs:string">
            <xs:pattern value="([a-zA-Z0-9/_-]{1,})\.(jpg|png)"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="displayType">
        <xs:sequence>
            <xs:element name="type" type="xs:string"/>
            <xs:element name="size" type="xs:decimal"/>
            <xs:element name="resolution" type="resolutionType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="resolutionType">
        <xs:sequence>
            <xs:element name="width" type="xs:decimal"/>
            <xs:element name="height" type="xs:decimal"/>
            <xs:element name="aspect_ratio" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="chipsetType">
        <xs:sequence>
            <xs:element name="brand" type="xs:string"/>
            <xs:element name="model" type="xs:string"/>
            <xs:element name="cores" type="coresType"/>
            <xs:element name="gpu" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="coresType">
        <xs:sequence>
            <xs:element name="core" type="coreType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="coreType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="frequency" type="frequencyType"/>
            <xs:element name="quantity" type="xs:decimal"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="frequencyType">
        <xs:simpleContent>
            <xs:extension base="xs:decimal">
                <xs:attribute name="unit" type="frequencyUnitType" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="frequencyUnitType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="GHz"/>
            <xs:enumeration value="MHz"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="camerasType">
        <xs:sequence>
            <xs:element name="rear" type="cameraPositionType" minOccurs="0"/>
            <xs:element name="front" type="cameraPositionType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="cameraPositionType">
        <xs:sequence>
            <xs:element name="camera" type="cameraType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="cameraType">
        <xs:sequence>
            <xs:element name="resolution" type="xs:decimal"/>
            <xs:element name="focallength" type="xs:decimal" minOccurs="0"/>
            <xs:element name="aperture" type="xs:string" minOccurs="0"/>
            <xs:element name="category" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="memoryType">
        <xs:sequence>
            <xs:element name="ram" type="ramType"/>
            <xs:element name="internal" type="internalType"/>
            <xs:element name="expansionslot" type="expansionslotType" minOccurs="0"> </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ramType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="unit" type="memoryUnitType" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="internalType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="unit" type="memoryUnitType" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="memoryUnitType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="TB"/>
            <xs:enumeration value="GB"/>
            <xs:enumeration value="MB"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="expansionslotType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="microSDHC"/>
            <xs:enumeration value="microSDXC"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="systemType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="version" type="xs:string"/>
            <xs:element name="overlay" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="batteryType">
        <xs:sequence>
            <xs:element name="size" type="xs:decimal"/>
            <xs:element name="charging" type="chargingType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="chargingType">
        <xs:sequence>
            <xs:element name="wired" type="xs:decimal"/>
            <xs:element name="wireless" type="xs:decimal" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="connectorsType">
        <xs:sequence>
            <xs:element name="connector" type="connectorType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="connectorType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="USB-C"/>
            <xs:enumeration value="microUSB"/>
            <xs:enumeration value="Lightning"/>
            <xs:enumeration value="3.5mm jack"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="commsType">
        <xs:sequence>
            <xs:sequence>
                <xs:element name="comm" type="xs:string" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="featuresType">
        <xs:sequence>
            <xs:sequence>
                <xs:element name="feature" type="xs:string" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="bodyType">
        <xs:sequence>
            <xs:element name="dimensions" type="dimensionsType"/>
            <xs:element name="weight" type="xs:decimal"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="dimensionsType">
        <xs:sequence>
            <xs:element name="height" type="xs:decimal"/>
            <xs:element name="width" type="xs:decimal"/>
            <xs:element name="depth" type="xs:decimal"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="categoriesType">
        <xs:sequence>
            <xs:element name="category" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== vojtechnerad/mobile-catalog/dokument.xml
<?xml version="1.0" encoding="UTF-8"?>
<devices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://example.com/nerv01/mobilni-katalog schema.xsd"
    xmlns="http://example.com/nerv01/mobilni-katalog">

    <manufacturers>
        <manufacturer>Samsung</manufacturer>
        <manufacturer>Apple</manufacturer>
        <manufacturer>OnePlus</manufacturer>
        <manufacturer>Nokia</manufacturer>
        <manufacturer>Cat</manufacturer>
    </manufacturers>

    <device id="1">
        <brand>Samsung</brand>
        <model>
            <name>Galaxy S10e</name>
            <code>SM-G970F</code>
        </model>
        <releasedate>2019-03-08</releasedate>
        <color>Prism Black</color>
        <price currency="CZK">9999</price>
        <image src="img/SM-G970F.png"/>

        <display>
            <type>AMOLED</type>
            <size>5.8</size>
            <resolution>
                <width>1080</width>
                <height>2280</height>
                <aspect_ratio>19:9</aspect_ratio>
            </resolution>
        </display>

        <chipset>
            <brand>Samsung</brand>
            <model>Exynos 9820</model>
            <cores>
                <core>
                    <name>Exynos M4</name>
                    <frequency unit="GHz">2.73</frequency>
                    <quantity>2</quantity>
                </core>
                <core>
                    <name>Cortex-A75</name>
                    <frequency unit="GHz">2.31</frequency>
                    <quantity>2</quantity>
                </core>
                <core>
                    <name>Cortex-A55</name>
                    <frequency unit="GHz">1.95</frequency>
                    <quantity>4</quantity>
                </core>
            </cores>
            <gpu>Mali-G76 MP12</gpu>
        </chipset>

        <cameras>
            <rear>
                <camera>
                    <resolution>12</resolution>
                    <focallength>26</focallength>
                    <aperture>1.5-2.4</aperture>
                    <category>Primární</category>
                </camera>

                <camera>
                    <resolution>16</resolution>
                    <focallength>12</focallength>
                    <aperture>2.2</aperture>
                    <category>Ultraširoká</category>
                </camera>
            </rear>

            <front>
                <camera>
                    <resolution>10</resolution>
                    <focallength>12</focallength>
                    <aperture>1.9</aperture>
                </camera>
            </front>
        </cameras>

        <memory>
            <ram unit="GB">6</ram>
            <internal unit="GB">128</internal>
            <expansionslot>microSDXC</expansionslot>
        </memory>

        <system>
            <name>Android</name>
            <version>9.0</version>
            <overlay>One UI 3.0</overlay>
        </system>

        <battery>
            <size>3100</size>
            <charging>
                <wired>15</wired>
                <wireless>15</wireless>
            </charging>
        </battery>

        <connectors>
            <connector>USB-C</connector>
            <connector>3.5mm jack</connector>
        </connectors>

        <comms>
            <comm>4G LTE</comm>
            <comm>Wi-Fi 6</comm>
            <comm>Bluetooth 5.0</comm>
            <comm>GPS</comm>
            <comm>NFC</comm>
        </comms>

        <features>
            <feature>Čtečka otisků</feature>
            <feature>Rychlé nabíjení</feature>
            <feature>Bezdrátové nabíjení</feature>
            <feature>Hlasový asistent Bixby</feature>
            <feature>Samsung Pay</feature>
        </features>

        <body>
            <dimensions>
                <height>142.2</height>
                <width>69.9</width>
                <depth>7.9</depth>
            </dimensions>
            <weight>150</weight>
        </body>

        <categories>
            <category>Dotykový</category>
        </categories>
    </device>

    <device id="2">
        <brand>Apple</brand>
        <model>
            <name>iPhone 11</name>
            <code>A2221</code>
        </model>
        <releasedate>2019-09-10</releasedate>
        <color>Red</color>
        <price currency="EUR">600</price>
        <image src="img/A2221.png"/>           

        <display>
            <type>Liquid Retina IPS LCD</type>
            <size>6.1</size>
            <resolution>
                <width>828</width>
                <height>1792</height>
                <aspect_ratio>19.5:9</aspect_ratio>
            </resolution>
        </display>

        <chipset>
            <brand>Apple</brand>
            <model>A13 Bionic</model>
            <cores>
                <core>
                    <name>Apple Thunder</name>
                    <frequency unit="GHz">1.8</frequency>
                    <quantity>4</quantity>
                </core>
                <core>
                    <name>Apple Lightning</name>
                    <frequency unit="GHz">2.65</frequency>
                    <quantity>2</quantity>
                </core>
            </cores>
            <gpu>Apple A13 Bionic GPU</gpu>
        </chipset>

        <cameras>
            <rear>
                <camera>
                    <resolution>12</resolution>
                    <focallength>26</focallength>
                    <aperture>1.8</aperture>
                    <category>Primární</category>
                </camera>

                <camera>
                    <resolution>12</resolution>
                    <focallength>13</focallength>
                    <aperture>2.4</aperture>
                    <category>Ultraširoká</category>
                </camera>
            </rear>

            <front>
                <camera>
                    <resolution>12</resolution>
                    <focallength>23</focallength>
                    <aperture>2.2</aperture>
                </camera>
            </front>
        </cameras>

        <memory>
            <ram unit="GB">4</ram>
            <internal unit="GB">64</internal>
        </memory>

        <system>
            <name>iOS</name>
            <version>13</version>
        </system>

        <battery>
            <size>3110</size>
            <charging>
                <wired>18</wired>
                <wireless>7.5</wireless>
            </charging>
        </battery>

        <connectors>
            <connector>Lightning</connector>
        </connectors>

        <comms>
            <comm>4G LTE</comm>
            <comm>Wi-Fi 6</comm>
            <comm>Bluetooth 5.0</comm>
            <comm>GPS</comm>
            <comm>NFC</comm>
        </comms>

        <features>
            <feature>Face ID</feature>
            <feature>Rychlé nabíjení</feature>
            <feature>Bezdrátové nabíjení</feature>
            <feature>Hlasový asistent Siri</feature>
            <feature>Apple Pay</feature>
        </features>

        <body>
            <dimensions>
                <height>150.9</height>
                <width>75.7</width>
                <depth>8.3</depth>
            </dimensions>
            <weight>194</weight>
        </body>

        <categories>
            <category>Dotykový</category>
        </categories>
    </device>

    <device id="3">
        <brand>Nokia</brand>
        <model>
            <name>6310 (2021)</name>
            <code>TA-1400</code>
        </model>
        <releasedate>2021-08-27</releasedate>
        <color>Green</color>
        <price currency="CZK">2000</price>
        <image src="img/TA-1400.png"/>

        <display>
            <type>TFT</type>
            <size>2.8</size>
            <resolution>
                <width>240</width>
                <height>320</height>
                <aspect_ratio>4:3</aspect_ratio>
            </resolution>
        </display>

        <chipset>
            <brand>Unisoc</brand>
            <model>6531F</model>
            <cores>
                <core>
                    <name>ARM926EJ-S</name>
                    <frequency unit="MHz">208</frequency>
                    <quantity>1</quantity>
                </core>
            </cores>
            <gpu>SC6531 GPU</gpu>
        </chipset>

        <cameras>
            <rear>
                <camera>
                    <resolution>0.3</resolution>
                    <category>Primární</category>
                </camera>
            </rear>
        </cameras>

        <memory>
            <ram unit="MB">8</ram>
            <internal unit="MB">16</internal>
            <expansionslot>microSDHC</expansionslot>
        </memory>

        <system>
            <name>Series</name>
            <version>30+</version>
        </system>

        <battery>
            <size>1150</size>
            <charging>
                <wired>18</wired>
            </charging>
        </battery>

        <connectors>
            <connector>microUSB</connector>
            <connector>3.5mm jack</connector>
        </connectors>

        <comms>
            <comm>2G GSM</comm>
            <comm>Wi-Fi 6</comm>
            <comm>Bluetooth 5.0</comm>
            <comm>GPS</comm>
            <comm>NFC</comm>
        </comms>

        <features>
            <feature>Face ID</feature>
            <feature>Rychlé nabíjení</feature>
            <feature>Bezdrátové nabíjení</feature>
            <feature>Hlasový asistent Siri</feature>
            <feature>Apple Pay</feature>
        </features>

        <body>
            <dimensions>
                <height>142.2</height>
                <width>69.9</width>
                <depth>7.9</depth>
            </dimensions>
            <weight>150</weight>
        </body>

        <categories>
            <category>Tlačítkový</category>
        </categories>
    </device>

    <device id="4">
        <brand>Cat</brand>
        <model>
